version: '3.7'
services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/voucher_system
    secrets:
      - jwt_secret
    depends_on:
      - mongodb
  client:
    build: ./client
    ports:
      - "8081:8081"
    environment:
      - API_URL=http://server:3001
    depends_on:
      - server
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:

secrets:
  jwt_secret:
    external: true
